DELETE FROM order_books WHERE 1;
DELETE FROM book_authors WHERE 1;
DELETE FROM authors WHERE 1;
DELETE FROM publishers WHERE 1;
DELETE FROM orders WHERE 1;
DELETE FROM books WHERE 1;
DELETE FROM clients WHERE 1;
